name: Run tests
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_call:

jobs:
  
  linux-tests:
    strategy:
      fail-fast: false
      matrix: 
        swiftver:
          - swift:5.4
          - swift:5.6
          - swiftlang/swift:nightly-5.7
        swiftplat:
          - focal
    runs-on: ubuntu-latest
    container: ${{ format('{0}-{1}', matrix.swiftver, matrix.swiftplat) }}
    steps:
      - name: Check out package
        uses: actions/checkout@v3
      - name: Run tests
        env:
          SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --enable-code-coverage
      - name: Submit code coverage data
        uses: vapor/swift-codecov-action@v0.2
        with:
          cc_env_vars: 'SWIFT_VERSION,SWIFT_PLATFORM,RUNNER_OS,RUNNER_ARCH'
          cc_fail_ci_if_error: true
          cc_verbose: true
  
  macos-tests:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest-stable
        macos:
          - macos-11
          - macos-12
        include:
          - macos: macos-12
            xcode: latest
    runs-on: ${{ matrix.macos }}
    steps:
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Check out package
        uses: actions/checkout@v3
      - name: Run tests
        env:
          SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test
